[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
